# Generated by Django 5.2.3 on 2025-06-24 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='Profile_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='Utilisateur_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='profile',
            field=models.ForeignKey(db_column='Profile_id', on_delete=django.db.models.deletion.CASCADE, to='monapp.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='utilisateur',
            field=models.OneToOneField(db_column='utilisateur_id', on_delete=django.db.models.deletion.CASCADE, to='monapp.utilisateur'),
        ),
    ]
